services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swingtails_backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./mi_base_vectorial:/app/mi_base_vectorial
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: swingtails_frontend
    ports:
      - "3000:3000"
    environment:
      - FASTAPI_URL=http://backend:8000
    depends_on:
      - backend
